# Generated by Django 4.1.2 on 2024-07-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
