# Generated by Django 4.1.2 on 2024-07-08 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_votos'),
        ('tienda', '0002_alter_obra_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
