# Generated by Django 4.1.2 on 2024-07-08 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_carrito_de_compra'),
        ('tienda', '0004_remove_artista_obras_obra_artista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='tienda.obra'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='usuarios.usuario'),
        ),
    ]
