# Generated by Django 4.1.2 on 2024-06-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0003_obradearte_delete_alumno_delete_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obradearte',
            name='apellido_artista',
        ),
        migrations.RemoveField(
            model_name='obradearte',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='obradearte',
            name='id_obra',
        ),
        migrations.RemoveField(
            model_name='obradearte',
            name='nombre_artista',
        ),
        migrations.RemoveField(
            model_name='obradearte',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='obradearte',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='obradearte',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='obradearte',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='obradearte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='obras_de_arte/'),
        ),
        migrations.AlterField(
            model_name='obradearte',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
