# Generated by Django 4.1.2 on 2024-07-08 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tienda', '0002_alter_obra_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito_de_Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('comprado', 'Comprado')], max_length=100)),
                ('total', models.IntegerField(max_length=100)),
                ('productos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.obra')),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito_de_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.carrito_de_compra')),
                ('direcciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.direccion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('votos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.voto')),
            ],
        ),
    ]
