# Generated by Django 4.1.2 on 2024-07-08 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='votos',
        ),
    ]
