# Generated by Django 4.1.2 on 2024-07-08 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_usuario_votos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='carrito_de_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.carrito_de_compra'),
        ),
    ]
