# Generated by Django 5.0.6 on 2024-07-08 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_carrito_de_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='carrito_de_compra',
        ),
        migrations.DeleteModel(
            name='Carrito_de_Compra',
        ),
    ]
