# Generated by Django 4.1.2 on 2024-06-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObraDeArte',
            fields=[
                ('id_obra', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('nombre_artista', models.CharField(max_length=100)),
                ('apellido_artista', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='obras/')),
            ],
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
    ]
